---
abstract: 'Bond git and Perl::Critic to blame the right people for violations.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  File::Path: '0'
  Test::Deep: '0'
  Test::Exception: '0'
  Test::FailWarnings: '0'
  Test::Git: '0'
  Test::More: '0'
  Test::Requires::Git: '1.005'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Critic-Git
provides:
  Perl::Critic::Git:
    file: lib/Perl/Critic/Git.pm
    version: v1.3.2
requires:
  Carp: '0'
  Data::Dumper: '0'
  File::Basename: '0'
  Git::Repository: '0'
  Git::Repository::Plugin::Blame: '0'
  Perl::Critic: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/guillaumeaubert/Perl-Critic-Git/issues
  homepage: https://metacpan.org/release/Perl-Critic-Git
  repository: https://github.com/guillaumeaubert/Perl-Critic-Git
version: v1.3.2
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
